// Son guncelleme: 2026-04-21 10:07
// Toplam: 64 eslesme
const BKU_DATA = [
  {
    "urun": "NİNJA 5 EC",
    "form": "EC",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "ARPA",
    "zararli": "Buğdaygil tripsleri",
    "phi": "28 gün",
    "doz": "25 ml/da",
    "mrl": "0.5",
    "grup": "İnsektisit",
    "gecerlilik": "2026-05-31",
    "aciklama": "-"
  },
  {
    "urun": "NİNJA 5 EC",
    "form": "EC",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "BUĞDAY ",
    "zararli": "Buğdaygil tripsleri",
    "phi": "28 gün",
    "doz": "25 ml/da",
    "mrl": "0.05",
    "grup": "İnsektisit",
    "gecerlilik": "2026-05-31",
    "aciklama": "-"
  },
  {
    "urun": "NİNJA 5 EC",
    "form": "EC",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "ÇAVDAR",
    "zararli": "Buğdaygil tripsleri",
    "phi": "28 gün",
    "doz": "25 ml/da",
    "mrl": "0.05",
    "grup": "İnsektisit",
    "gecerlilik": "2026-05-31",
    "aciklama": "-"
  },
  {
    "urun": "NİNJA 5 EC",
    "form": "EC",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "YULAF",
    "zararli": "Buğdaygil tripsleri",
    "phi": "28 gün",
    "doz": "25 ml/da",
    "mrl": "0.3",
    "grup": "İnsektisit",
    "gecerlilik": "2026-05-31",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "TRABZON HURMASI",
    "zararli": "TRABZON HURMASINDA YAPRAK LEKESİ",
    "phi": "70 gün",
    "doz": "80-100 l/da (Dekara 50-100 L su ile )",
    "mrl": "0.01",
    "grup": "Fungisit",
    "gecerlilik": "2026-07-15",
    "aciklama": "Fitotoksisite riski bulunmaktadır, dormant dönemde kullanılmalıdır.Bitki koruma ürünü etiketinde yer alan kullanım uyarılarına dikkat edilmelidir."
  },
  {
    "urun": "QUADRİS MAXX",
    "form": "SC",
    "aktif": "200 g/l Azoxystrobin + 125 g/l Difenoconazole",
    "bitki": "GÜL (Süs bitkisi)",
    "zararli": "GÜL PASI",
    "phi": "14 gün",
    "doz": "100 ml/ 100 l su",
    "mrl": "Azoxystrobin:60 mg/kg, Difenoconazole:20 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-07-30",
    "aciklama": "-"
  },
  {
    "urun": "KARATE ZEON",
    "form": "CS",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "BİBER",
    "zararli": "Danaburnu",
    "phi": "21 gün",
    "doz": "40 ml/da",
    "mrl": "0,1",
    "grup": "İnsektisit",
    "gecerlilik": "2026-07-29",
    "aciklama": "-"
  },
  {
    "urun": "KARATE ZEON",
    "form": "CS",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "HIYAR",
    "zararli": "Danaburnu",
    "phi": "21 gün",
    "doz": "40 ml/da",
    "mrl": "0,005",
    "grup": "İnsektisit",
    "gecerlilik": "2026-07-29",
    "aciklama": "-"
  },
  {
    "urun": "KARATE ZEON",
    "form": "CS",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "LAHANA ",
    "zararli": "Danaburnu",
    "phi": "21 gün",
    "doz": "40 ml/da",
    "mrl": "0,15",
    "grup": "İnsektisit",
    "gecerlilik": "2026-07-29",
    "aciklama": "-"
  },
  {
    "urun": "KARATE ZEON",
    "form": "CS",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "MARUL",
    "zararli": "Danaburnu",
    "phi": "21 gün",
    "doz": "40 ml/da",
    "mrl": "0,15",
    "grup": "İnsektisit",
    "gecerlilik": "2026-07-29",
    "aciklama": "-"
  },
  {
    "urun": "KARATE ZEON",
    "form": "CS",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "PATATES",
    "zararli": "Danaburnu",
    "phi": "21 gün",
    "doz": "40 ml/da",
    "mrl": "0,01*",
    "grup": "İnsektisit",
    "gecerlilik": "2026-07-29",
    "aciklama": "-"
  },
  {
    "urun": "KARATE ZEON",
    "form": "CS",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "KABAK",
    "zararli": "Danaburnu",
    "phi": "21 gün",
    "doz": "40 ml/da",
    "mrl": "0,15",
    "grup": "İnsektisit",
    "gecerlilik": "2026-07-29",
    "aciklama": "-"
  },
  {
    "urun": "KARATE ZEON",
    "form": "CS",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "KAVUN",
    "zararli": "Danaburnu",
    "phi": "21 gün",
    "doz": "40 ml/da",
    "mrl": "0,06",
    "grup": "İnsektisit",
    "gecerlilik": "2026-07-29",
    "aciklama": "-"
  },
  {
    "urun": "KARATE ZEON",
    "form": "CS",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "DOMATES",
    "zararli": "Danaburnu",
    "phi": "21 gün",
    "doz": "40 ml/da",
    "mrl": "0,007",
    "grup": "İnsektisit",
    "gecerlilik": "2026-07-29",
    "aciklama": "-"
  },
  {
    "urun": "KARATE ZEON",
    "form": "CS",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "KARPUZ",
    "zararli": "Danaburnu",
    "phi": "21 gün",
    "doz": "40 ml/da",
    "mrl": "0,06",
    "grup": "İnsektisit",
    "gecerlilik": "2026-07-29",
    "aciklama": "-"
  },
  {
    "urun": "KARATE ZEON",
    "form": "CS",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "PATLICAN",
    "zararli": "Danaburnu",
    "phi": "21 gün",
    "doz": "40 ml/da",
    "mrl": "0,3",
    "grup": "İnsektisit",
    "gecerlilik": "2026-07-29",
    "aciklama": "-"
  },
  {
    "urun": "SWITCH 62.5 WG",
    "form": "WG",
    "aktif": "%37,5 Cyprodinil + %25 Fludioxonil",
    "bitki": "GÜL (Süs bitkisi)",
    "zararli": "Kurşuni küf",
    "phi": "14 gün",
    "doz": "80 g/100 l su",
    "mrl": "Cyprodinil:0.1* Fludioxonil:0,05*",
    "grup": "Fungisit",
    "gecerlilik": "2026-07-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "ANASON",
    "zararli": "Anason yaprak lekesi",
    "phi": "-",
    "doz": "66 ml/100 kg tohuma",
    "mrl": "0.3 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-07-31",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "ANASON",
    "zararli": "Anason yaprak lekesi",
    "phi": "-",
    "doz": "60 ml/da",
    "mrl": "0.3 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-07-31",
    "aciklama": "-"
  },
  {
    "urun": "CELEST MAX 100 FS",
    "form": "FS",
    "aktif": "100 g/l Fludioxonil",
    "bitki": "KİMYON",
    "zararli": "Kök çürüklüğü hastalığı",
    "phi": "-",
    "doz": "10 ml/100 kg tohuma",
    "mrl": "0.05* mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-07-29",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "KİMYON",
    "zararli": "Alternaria yaprak lekesi",
    "phi": "35 gün",
    "doz": "112,5 (yüz on iki buçuk) ml/dekar",
    "mrl": "0.3 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-07-29",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS MAXX",
    "form": "SC",
    "aktif": "200 g/l Azoxystrobin + 125 g/l Difenoconazole",
    "bitki": "GÜL (Süs bitkisi)",
    "zararli": "Gülde karaleke",
    "phi": "14 gün",
    "doz": "100 ml/ 100 l su",
    "mrl": "Azoxystrobin:60 mg/kg, Difenoconazole:20 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-07-30",
    "aciklama": "-"
  },
  {
    "urun": "NİNJA 5 EC",
    "form": "EC",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "AVOKADO",
    "zararli": "İncir Teke Böceği",
    "phi": "7 Gün",
    "doz": "20 ml/100 L su",
    "mrl": "0,15",
    "grup": "İnsektisit",
    "gecerlilik": "2026-07-15",
    "aciklama": "-"
  },
  {
    "urun": "AMPLİGO 150 ZC",
    "form": "ZC",
    "aktif": "100 g/l Chlorantraniliprole + 50 g/l Lambda-cyhalothrin",
    "bitki": "AVOKADO",
    "zararli": "İncir Teke Böceği",
    "phi": "14 Gün",
    "doz": "50 ml/100 L su",
    "mrl": "Chlorantraniliprole: 0,3 Lambda-cyhalothrin:0,15",
    "grup": "İnsektisit",
    "gecerlilik": "2026-07-15",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "HAŞHAŞ ",
    "zararli": "Haşhaş mildiyösü",
    "phi": "35 gün",
    "doz": "40-105 ml/da",
    "mrl": "0.5 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-07-15",
    "aciklama": "-"
  },
  {
    "urun": "NİNJA 5 EC",
    "form": "EC",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "KANOLA",
    "zararli": "Lahana yaprakgüvesi",
    "phi": "21 gün",
    "doz": "100 ml/da",
    "mrl": "0,2",
    "grup": "İnsektisit",
    "gecerlilik": "2026-07-12",
    "aciklama": "-"
  },
  {
    "urun": "KARATE ZEON",
    "form": "CS",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "KANOLA",
    "zararli": "Yaprakbiti",
    "phi": "21 gün",
    "doz": "70 ml/da",
    "mrl": "0,2",
    "grup": "İnsektisit",
    "gecerlilik": "2026-06-28",
    "aciklama": "-"
  },
  {
    "urun": "PLOCAFİR",
    "form": "EW",
    "aktif": "700 g/l Mineral Yağ",
    "bitki": "ERİK",
    "zararli": "ERİK KOŞNİLİ",
    "phi": "-",
    "doz": "1500 ml/100 L su",
    "mrl": "MRL uygulanmaz.",
    "grup": "İnsektisit",
    "gecerlilik": "2026-06-29",
    "aciklama": "-"
  },
  {
    "urun": "FORTENZA 600 FS",
    "form": "FS",
    "aktif": "600 g/l Cyantraniliprole",
    "bitki": "PATATES",
    "zararli": "Telkurtları",
    "phi": "28 gün",
    "doz": "22.5 ml/100 kg tohum",
    "mrl": "0,15",
    "grup": "İnsektisit",
    "gecerlilik": "2026-06-30",
    "aciklama": "Afyonkarahisar ili için geçici kullanım izni verilmiştir."
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "ENGİNAR",
    "zararli": "Toprak kökenli patojenler",
    "phi": "14",
    "doz": "45 ml/da",
    "mrl": "5 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-05-31",
    "aciklama": "Aydın ili için geçici kullanım izni verilmiştir."
  },
  {
    "urun": "PLOCAFİR",
    "form": "EW",
    "aktif": "700 g/l Mineral Yağ",
    "bitki": "AHUDUDU VE BÖĞÜRTLEN",
    "zararli": "Turunçgil unlubiti",
    "phi": "-",
    "doz": "1000 ml/100 l su",
    "mrl": "-",
    "grup": "İnsektisit",
    "gecerlilik": "2026-05-16",
    "aciklama": "-"
  },
  {
    "urun": "PLOCAFİR",
    "form": "EW",
    "aktif": "700 g/l Mineral Yağ",
    "bitki": "YABAN MERSİNİ",
    "zararli": "Turunçgil unlubiti",
    "phi": "-",
    "doz": "1000 ml/100 l su",
    "mrl": "-",
    "grup": "İnsektisit",
    "gecerlilik": "2026-05-16",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "MARUL",
    "zararli": "Sebzelerde septorya yaprak lekesi",
    "phi": "14",
    "doz": "45 ml/da",
    "mrl": "10 mg / kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "FESLEĞEN",
    "zararli": "Sebzelerde septorya yaprak lekesi",
    "phi": "14 gün",
    "doz": "45 ml/da",
    "mrl": "70 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "DEREOTU",
    "zararli": "Sebzelerde septorya yaprak lekesi",
    "phi": "14 gün",
    "doz": "45 ml/da",
    "mrl": "70 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "APRIN XL 350 ES",
    "form": "ES",
    "aktif": "350 g/l Metalaxyl-m",
    "bitki": "MAYDANOZ",
    "zararli": "Toprak kökenli patojenler",
    "phi": "-",
    "doz": "50 ml/100 kg tohum",
    "mrl": "3 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "APRIN XL 350 ES",
    "form": "ES",
    "aktif": "350 g/l Metalaxyl-m",
    "bitki": "ROKA",
    "zararli": "Toprak kökenli patojenler",
    "phi": "-",
    "doz": "50 ml/100 kg tohum",
    "mrl": "3 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "APRIN XL 350 ES",
    "form": "ES",
    "aktif": "350 g/l Metalaxyl-m",
    "bitki": "TERE",
    "zararli": "Toprak kökenli patojenler",
    "phi": "-",
    "doz": "50 ml/100 kg tohum",
    "mrl": "3 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "APRIN XL 350 ES",
    "form": "ES",
    "aktif": "350 g/l Metalaxyl-m",
    "bitki": "NANE",
    "zararli": "Toprak kökenli patojenler",
    "phi": "-",
    "doz": "50 ml/100 kg tohum",
    "mrl": "3 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "APRIN XL 350 ES",
    "form": "ES",
    "aktif": "350 g/l Metalaxyl-m",
    "bitki": "DEREOTU",
    "zararli": "Toprak kökenli patojenler",
    "phi": "-",
    "doz": "50 ml/100 kg tohum",
    "mrl": "3 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "APRIN XL 350 ES",
    "form": "ES",
    "aktif": "350 g/l Metalaxyl-m",
    "bitki": "FESLEĞEN",
    "zararli": "Toprak kökenli patojenler",
    "phi": "-",
    "doz": "50 ml/100 kg tohum",
    "mrl": "3 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "SEMİZOTU",
    "zararli": "Mildiyö",
    "phi": "14",
    "doz": "45 ml/da",
    "mrl": "15 mg / kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "TERE",
    "zararli": "Mildiyö",
    "phi": "14 gün",
    "doz": "45 ml/da",
    "mrl": "10 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "MAYDANOZ",
    "zararli": "Mildiyö",
    "phi": "14 gün",
    "doz": "45 ml/da",
    "mrl": "70 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "DEREOTU",
    "zararli": "Mildiyö",
    "phi": "14 gün",
    "doz": "45 ml/da",
    "mrl": "70 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "ROKA",
    "zararli": "Mildiyö",
    "phi": "14 gün",
    "doz": "45 ml/da",
    "mrl": "10 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "TERE",
    "zararli": "Alternaria yaprak lekesi",
    "phi": "14 gün",
    "doz": "45 ml/da",
    "mrl": "10 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "ROKA",
    "zararli": "Alternaria yaprak lekesi",
    "phi": "14 gün",
    "doz": "45 ml/da",
    "mrl": "10 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "DEREOTU",
    "zararli": "Alternaria yaprak lekesi",
    "phi": "14 gün",
    "doz": "45 ml/da",
    "mrl": "70 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "SEMİZOTU",
    "zararli": "Alternaria yaprak lekesi",
    "phi": "14 gün",
    "doz": "45 ml/da",
    "mrl": "15 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "FESLEĞEN",
    "zararli": "Alternaria yaprak lekesi",
    "phi": "14 gün",
    "doz": "45 ml/da",
    "mrl": "70 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "MARUL",
    "zararli": "Alternaria yaprak lekesi",
    "phi": "14",
    "doz": "45 ml/da",
    "mrl": "10 mg / kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "SEMİZOTU",
    "zararli": "Sebzelerde septorya yaprak lekesi",
    "phi": "14 gün",
    "doz": "45 ml/da",
    "mrl": "15 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "ROKA",
    "zararli": "Sebzelerde septorya yaprak lekesi",
    "phi": "14 gün",
    "doz": "45 ml/da",
    "mrl": "10 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "FESLEĞEN",
    "zararli": "MİLDİYÖ",
    "phi": "14",
    "doz": "45 ml/da",
    "mrl": "70 mg / kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "ISPANAK",
    "zararli": "Yaprağı Yenen Sebzelerde Beyaz Pas",
    "phi": "14 gün",
    "doz": "45 ml / da",
    "mrl": "15 mg / kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "SEMİZOTU",
    "zararli": "Yaprağı Yenen Sebzelerde Beyaz Pas",
    "phi": "14 gün",
    "doz": "45 ml / da",
    "mrl": "15 mg / kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "DEREOTU",
    "zararli": "Yaprağı Yenen Sebzelerde Beyaz Pas",
    "phi": "14 gün",
    "doz": "45 ml / da",
    "mrl": "70 mg / kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "NANE",
    "zararli": "Yaprağı Yenen Sebzelerde Beyaz Pas",
    "phi": "14 gün",
    "doz": "45 ml/da",
    "mrl": "70 mg/kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "MARUL",
    "zararli": "KÜLLEME",
    "phi": "14",
    "doz": "45 ml/da",
    "mrl": "10 mg / kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "FESLEĞEN",
    "zararli": "KÜLLEME",
    "phi": "14",
    "doz": "45 ml/da",
    "mrl": "70 mg / kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "ISPANAK",
    "zararli": "KÜLLEME",
    "phi": "14",
    "doz": "45 ml/da",
    "mrl": "15 mg / kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "QUADRİS",
    "form": "SC",
    "aktif": "250 g/l Azoxystrobin",
    "bitki": "SEMİZOTU",
    "zararli": "KÜLLEME",
    "phi": "14",
    "doz": "45 ml/da",
    "mrl": "15 mg / kg",
    "grup": "Fungisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "-"
  },
  {
    "urun": "KARATE ZEON",
    "form": "CS",
    "aktif": "50 g/l Lambda-cyhalothrin ",
    "bitki": "ISPANAK",
    "zararli": "Pamuk yaprakkurdu",
    "phi": "7 Gün",
    "doz": "15 ml/da",
    "mrl": "0.6 mg/kg",
    "grup": "İnsektisit",
    "gecerlilik": "2026-04-30",
    "aciklama": "İzmir ve Manisa illeri için geçici kullanım izni verilmiştir."
  }
];
